switch to use nvcc
open-ce/tensorrt-feedstock pull request #6
Opened 2020-09-30 21:33 UTC by jayfurmanek

This switches the TRT recipe to use the `nvcc` metapackage instead of `cudatoolkit-dev`

requires: 
https://github.com/open-ce/nvcc-feedstock/pull/3

2020-10-01 18:37 UTC, bnemanich approved these changes

2020-10-05 13:29 UTC, npanpaliya requested changes

2020-10-05 13:29 UTC, npanpaliya commented on tensorrt/0204-update-Makefile.conf-for-conda-builds.patch
> +@@ -10,9 +10,9 @@ ifeq ($(CUDNN_INSTALL_DIR),)
These file path changes are causing the build failure.

2020-10-10 09:47 UTC, npanpaliya approved these changes

2020-10-12 08:04 UTC, npanpaliya commented
Should build number be incremented for uff and graphsurgeon too?

2020-10-14 14:26 UTC, merged